# Generated by Django 5.2.14 on 2026-06-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_burnneweden', '0002_refactor_contract_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'default_permissions': (), 'permissions': (('basic_access', 'Can access the Burn New Eden app'), ('puller_access', 'Puller: can view own submitted contracts'), ('runner_access', 'Runner: can view and accept open contracts'), ('staff_access', 'Staff: can manage all contracts'), ('admin_access', 'Admin: full access including configuration'))},
        ),
        migrations.RemoveConstraint(
            model_name='contract',
            name='unique_contract_per_corp',
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ownercorporation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('owner_corporation', 'contract_id')},
        ),
    ]
