# Generated by Django 5.2.14 on 2026-06-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_burnneweden', '0003_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ownercorporation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
