# Generated by Django 5.2.14 on 2026-06-04 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_burnneweden', '0004_alter_contract_id_alter_contractitem_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discord_dm_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DiscordNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_contract_created', models.BooleanField(default=False)),
                ('notify_contract_started', models.BooleanField(default=False)),
                ('notify_contract_rejected', models.BooleanField(default=False)),
                ('notify_contract_completed', models.BooleanField(default=False)),
                ('notify_new_open_contracts', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burner_discord_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord Notification Preference',
                'default_permissions': (),
            },
        ),
    ]
